_config.yml, layout/includes/comments/disqus.pug, layout/includes/comments/disqusjs.pug, layout/includes/comments/index.pug
修改 Disqus 为 Disqus.js 版评论系统，应对大陆长城的折中方案，兼容原版。
[https://github.com/SukkaW/DisqusJS](https://github.com/SukkaW/DisqusJS )
=> 修改 Disqus 为 Disqus.js 版

_config.yml, layout/includes/comments/gitalk.pug
add `createIssueManually` and `distractionFreeMode` to gitalk
=> add more options to gitalk

layout/includes/head/analytics.pug
=> Fix Tencent Analytics #105

_config.yml, languages/default.yml, languages/en.yml, languages/zh-CN.yml, languages/zh-TW.yml, layout/includes/footer.pug
- 頁腳的作者信息可以選擇是否開啟
- 頁腳 Hexo 前面的 Driven(驅動) 改成 Framework(框架) 應該更好一些
- 中文的搜索欄 hits_empty，冒號應該用全角
- 更正一些小的打字錯誤
=> 整理 footer 配置項，同時修改部分用语

layout/includes/widget/card_author.pug
Reverts jerryc127/hexo-theme-butterfly#358
=> Revert "Add a flag for allowing to disable aside.card_author.button"

layout/404.pug, layout/includes/header/index.pug, layout/includes/layout.pug
貼文的封面圖正常是這樣的格式 background-image: url(http://mydomain.com/xx.jpg)
可是當該檔名存在括號「"("、")"」時，則會截斷「url」後的括號，舉例：background-image: url(http://mydomain.com/x()x.jpg)
這麼一來則會無法正常讀取圖檔。
=> bg-image: url('')

_config.yml, languages/default.yml, languages/en.yml, languages/zh-CN.yml, languages/zh-TW.yml, layout/includes/header/index.pug, layout/includes/header/post-info.pug, scripts/helpers/page.js, source/css/_layout/head.styl
=> feat: Post edit Easily browse and edit blog source code online

_config.yml
=> 【修复】HPP使用最新版本

layout/includes/header/post-info.pug
https://valine.js.org/visitor.html
裡面有data-flag-title="Your Article Title"
leancloud 應用創建Counter類會存文章標題
=> Improvement valine visitor 

source/css/_layout/post.styl, source/css/_mode/darkmode.styl, source/css/_mode/readmode.styl
Add the layout of 'kbd' tag.
You can check the style on my post [here](https://blog.gztime.cc/posts/2020/6b9b4626/).
Some 'kbd' tags are used in this post.
=> Add the layout of kbd tag

_config.yml, layout/includes/third-party/comments/twikoo.pug
improvement: 搜索和字数统计两个功能添加相应文档地址注释 (太多新人因为这两报错然后到群里问了)
=> fix: twikoo 评论区表情包去除灯箱渲染

_config.yml, layout/includes/third-party/subtitle.pug
想直接在 _config.yml 設定副標題打字效果速度就寫了，
沒在 _config.yml 加入註解看作者覺得會不會太冗長，
我覺得調整速度應該蠻多人想要的。
=> feat: Support typewriter effect speed options of Subtitle in _config.yml

source/js/main.js
修復屏幕寬度爲 768px 時的佈局混用問題
現狀：
寬度 769px：PC 佈局
寬度 768px：移動端佈局，但保留了 PC 佈局的菜單
寬度 767px：完全的移動端佈局
=> fix: fix mixed layout when screen eq 768px

source/js/main.js
只有在调用`throttle`返回的同一个对象时才能起到“节流”效果。
=> 修正`throttle`函数调用方式

layout/includes/head.pug
详情链接：https://www.omiod.com/meta-seo-inspector/meta-info.php?meta=viewport&utm_source=MSI_app&utm_medium=info_link&utm_term=viewport
SEO 检查工具发现的问题：
=> chore: 优化 viewport seo

_config.yml, scripts/helpers/inject_head_js.js
=> 新增自定义深浅模式切换时间

layout/includes/page/flink.pug
在 Frontmatter 中配置 `random: true` 就随机显示，默认按顺序
=> feat: 支持随机友链顺序

layout/includes/footer.pug
since设置为false即不显示since年份，否则正常显示
=> 允许不显示footer中的since年份

layout/includes/footer.pug
Reverts jerryc127/hexo-theme-butterfly#1309
=> Revert "允许不显示footer中的since年份"

layout/includes/third-party/subtitle.pug
The link seems to be written incorrectly.
=> fix(subtitle): fix the wrong subtitle link
